version: "3.9"
services:
  land_service:
    image: jinergenkai/hh-land-service
    container_name: land_service
    build: .
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - mongo_land
    environment:
      MONGO_URI: "mongodb://admin:password@mongo_land:27017/"
    networks:
      - kong_net 
  
  mongo_land:
    image: mongo:8.0
    container_name: mongo_land
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    networks:
      - kong_net

volumes:
  mongo_data:

networks:
  kong_net:
    external: true